// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/db/interfaces.go
//
// Generated by this command:
//
//	mockgen -package db -source pkg/db/interfaces.go -destination pkg/db/interfaces_mock.go
//

// Package db is a generated GoMock package.
package db

import (
	context "context"
	reflect "reflect"

	v5 "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	pgxpool "github.com/jackc/pgx/v5/pgxpool"
	gomock "go.uber.org/mock/gomock"
)

// MockPgxScanner is a mock of PgxScanner interface.
type MockPgxScanner struct {
	ctrl     *gomock.Controller
	recorder *MockPgxScannerMockRecorder
}

// MockPgxScannerMockRecorder is the mock recorder for MockPgxScanner.
type MockPgxScannerMockRecorder struct {
	mock *MockPgxScanner
}

// NewMockPgxScanner creates a new mock instance.
func NewMockPgxScanner(ctrl *gomock.Controller) *MockPgxScanner {
	mock := &MockPgxScanner{ctrl: ctrl}
	mock.recorder = &MockPgxScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPgxScanner) EXPECT() *MockPgxScannerMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *MockPgxScanner) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockPgxScannerMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockPgxScanner)(nil).Scan), dest...)
}

// MockIQuery is a mock of IQuery interface.
type MockIQuery struct {
	ctrl     *gomock.Controller
	recorder *MockIQueryMockRecorder
}

// MockIQueryMockRecorder is the mock recorder for MockIQuery.
type MockIQueryMockRecorder struct {
	mock *MockIQuery
}

// NewMockIQuery creates a new mock instance.
func NewMockIQuery(ctrl *gomock.Controller) *MockIQuery {
	mock := &MockIQuery{ctrl: ctrl}
	mock.recorder = &MockIQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIQuery) EXPECT() *MockIQueryMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockIQuery) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range arguments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockIQueryMockRecorder) Exec(ctx, sql any, arguments ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, arguments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockIQuery)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockIQuery) Query(ctx context.Context, sql string, args ...any) (v5.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(v5.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockIQueryMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockIQuery)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockIQuery) QueryRow(ctx context.Context, sql string, args ...any) v5.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(v5.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockIQueryMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockIQuery)(nil).QueryRow), varargs...)
}

// MockTxRepository is a mock of TxRepository interface.
type MockTxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTxRepositoryMockRecorder
}

// MockTxRepositoryMockRecorder is the mock recorder for MockTxRepository.
type MockTxRepositoryMockRecorder struct {
	mock *MockTxRepository
}

// NewMockTxRepository creates a new mock instance.
func NewMockTxRepository(ctrl *gomock.Controller) *MockTxRepository {
	mock := &MockTxRepository{ctrl: ctrl}
	mock.recorder = &MockTxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxRepository) EXPECT() *MockTxRepositoryMockRecorder {
	return m.recorder
}

// GetDb mocks base method.
func (m *MockTxRepository) GetDb(ctx context.Context) IQuery {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDb", ctx)
	ret0, _ := ret[0].(IQuery)
	return ret0
}

// GetDb indicates an expected call of GetDb.
func (mr *MockTxRepositoryMockRecorder) GetDb(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDb", reflect.TypeOf((*MockTxRepository)(nil).GetDb), ctx)
}

// GetNative mocks base method.
func (m *MockTxRepository) GetNative() *pgxpool.Pool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNative")
	ret0, _ := ret[0].(*pgxpool.Pool)
	return ret0
}

// GetNative indicates an expected call of GetNative.
func (mr *MockTxRepositoryMockRecorder) GetNative() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNative", reflect.TypeOf((*MockTxRepository)(nil).GetNative))
}

// Lock mocks base method.
func (m *MockTxRepository) Lock(ctx context.Context, table, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", ctx, table, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lock indicates an expected call of Lock.
func (mr *MockTxRepositoryMockRecorder) Lock(ctx, table, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockTxRepository)(nil).Lock), ctx, table, code)
}

// TryLock mocks base method.
func (m *MockTxRepository) TryLock(ctx context.Context, table, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryLock", ctx, table, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryLock indicates an expected call of TryLock.
func (mr *MockTxRepositoryMockRecorder) TryLock(ctx, table, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryLock", reflect.TypeOf((*MockTxRepository)(nil).TryLock), ctx, table, code)
}

// TxLock mocks base method.
func (m *MockTxRepository) TxLock(ctx context.Context, table, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxLock", ctx, table, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// TxLock indicates an expected call of TxLock.
func (mr *MockTxRepositoryMockRecorder) TxLock(ctx, table, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxLock", reflect.TypeOf((*MockTxRepository)(nil).TxLock), ctx, table, code)
}

// Unlock mocks base method.
func (m *MockTxRepository) Unlock(ctx context.Context, table, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock", ctx, table, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unlock indicates an expected call of Unlock.
func (mr *MockTxRepositoryMockRecorder) Unlock(ctx, table, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockTxRepository)(nil).Unlock), ctx, table, code)
}

// WithTx mocks base method.
func (m *MockTxRepository) WithTx(ctx context.Context, handler func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTxRepositoryMockRecorder) WithTx(ctx, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTxRepository)(nil).WithTx), ctx, handler)
}
