// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/app_runner/apps.go
//
// Generated by this command:
//
//	mockgen -package app_runner -source pkg/app_runner/apps.go -destination pkg/app_runner/apps_mock.go
//

// Package app_runner is a generated GoMock package.
package app_runner

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// Shutdown mocks base method.
func (m *MockApp) Shutdown() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown")
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockAppMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockApp)(nil).Shutdown))
}

// Start mocks base method.
func (m *MockApp) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockAppMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockApp)(nil).Start), ctx)
}

// MockAppsRunner is a mock of AppsRunner interface.
type MockAppsRunner struct {
	ctrl     *gomock.Controller
	recorder *MockAppsRunnerMockRecorder
}

// MockAppsRunnerMockRecorder is the mock recorder for MockAppsRunner.
type MockAppsRunnerMockRecorder struct {
	mock *MockAppsRunner
}

// NewMockAppsRunner creates a new mock instance.
func NewMockAppsRunner(ctrl *gomock.Controller) *MockAppsRunner {
	mock := &MockAppsRunner{ctrl: ctrl}
	mock.recorder = &MockAppsRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppsRunner) EXPECT() *MockAppsRunnerMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockAppsRunner) Register(name string, start starter, shutdown shutdowner) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", name, start, shutdown)
}

// Register indicates an expected call of Register.
func (mr *MockAppsRunnerMockRecorder) Register(name, start, shutdown any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAppsRunner)(nil).Register), name, start, shutdown)
}

// RegisterApp mocks base method.
func (m *MockAppsRunner) RegisterApp(name string, instance App) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterApp", name, instance)
}

// RegisterApp indicates an expected call of RegisterApp.
func (mr *MockAppsRunnerMockRecorder) RegisterApp(name, instance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterApp", reflect.TypeOf((*MockAppsRunner)(nil).RegisterApp), name, instance)
}

// Run mocks base method.
func (m *MockAppsRunner) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockAppsRunnerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockAppsRunner)(nil).Run), ctx)
}
